version: '3'

services:
  pseudo_api:
    container_name: pseudo_api
    restart: always
    build: ./pseudo_api
    ports:
      - "8000:8000"
    volumes:
      - ${PSEUDO_MODEL_PATH}:/usr/src/pseudo_api/model/best-model.pt
      - ${PSEUDO_API_DB_PATH}:/usr/src/pseudo_api/api_stats.sqlite
    command: gunicorn -w 2 --timeout 90 -b 0.0.0.0:8000 wsgi:server

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - pseudo_api